### ISSUE TITLE
Android Studio build error 

### ISSUE THREAD

**Issue by bobjoe12131** [Blokkok/blokkok#3]
opened project in android studio to build it and got this error:

`Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :module-system.
     Required by:
         project :app
      > No matching configuration of project :module-system was found. The consumer was configured to find a runtime of a component, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
          - None of the consumable configurations have attributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

`

**Comment by iyxan23** [comment]
Hi, it seems that you have forgotten to update the submodules of the git repository. Blokkok uses a thing called "[git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules)" as you can see [here](https://github.com/Blokkok/blokkok/tree/stripped-modular/submodules), submodule is like referencing a different repository and embedding it inside a different repository. This submodule won't get updated automatically when you clone this repository, so you needed to update it yourselves by running this command on the project directory:
```console
$ git submodule update --init
```

**Comment by bobjoe12131** [comment]
Did that command and realized that I didn't do git lfs pull either so did that command, pressed build, got a different error:

Executing tasks: [:app:assembleDebug] in project C:\Users\Mark\Downloads\blokkok

Starting Gradle Daemon...
Gradle Daemon started in 5 s 62 ms
> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :module-system:preBuild UP-TO-DATE
> Task :module-system:preDebugBuild UP-TO-DATE
> Task :module-system:compileDebugAidl NO-SOURCE
> Task :app:compileDebugAidl NO-SOURCE
> Task :module-system:packageDebugRenderscript NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:dataBindingMergeDependencyArtifactsDebug UP-TO-DATE
> Task :app:dataBindingMergeGenClassesDebug UP-TO-DATE
> Task :app:generateDebugResValues UP-TO-DATE
> Task :app:generateDebugResources UP-TO-DATE
> Task :app:processDebugGoogleServices FAILED
> Task :module-system:compileDebugRenderscript NO-SOURCE
> Task :module-system:generateDebugResValues UP-TO-DATE
> Task :module-system:generateDebugResources UP-TO-DATE
> Task :module-system:packageDebugResources UP-TO-DATE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :module-system:writeDebugAarMetadata UP-TO-DATE
> Task :app:checkDebugAarMetadata UP-TO-DATE
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:extractDeepLinksDebug UP-TO-DATE
> Task :module-system:extractDeepLinksDebug UP-TO-DATE
> Task :module-system:processDebugManifest UP-TO-DATE
> Task :app:processDebugMainManifest UP-TO-DATE
> Task :app:processDebugManifest UP-TO-DATE
> Task :app:processDebugManifestForPackage UP-TO-DATE
> Task :module-system:compileDebugLibraryResources UP-TO-DATE
> Task :module-system:parseDebugLocalResources UP-TO-DATE
> Task :module-system:generateDebugRFile UP-TO-DATE
> Task :module-interface:compileKotlin UP-TO-DATE
> Task :module-interface:compileJava NO-SOURCE
> Task :module-interface:processResources NO-SOURCE
> Task :module-interface:classes UP-TO-DATE
> Task :module-interface:inspectClassesForKotlinIC UP-TO-DATE
> Task :module-interface:jar UP-TO-DATE
> Task :module-system:generateDebugBuildConfig UP-TO-DATE
> Task :module-system:javaPreCompileDebug UP-TO-DATE

> Task :module-system:compileDebugKotlin FAILED
e: C:\Users\Mark\Downloads\blokkok\submodules\blokkok-modsys\module-system\src\main\java\com\blokkok\modsys\communication\BroadcastCommunication.kt: (3, 41): Unresolved reference: objects
e: C:\Users\Mark\Downloads\blokkok\submodules\blokkok-modsys\module-system\src\main\java\com\blokkok\modsys\communication\BroadcastCommunication.kt: (4, 41): Unresolved reference: objects
e: C:\Users\Mark\Downloads\blokkok\submodules\blokkok-modsys\module-system\src\main\java\com\blokkok\modsys\communication\BroadcastCommunication.kt: (7, 22): Unresolved reference: Broadcaster
e: C:\Users\Mark\Downloads\blokkok\submodules\blokkok-modsys\module-system\src\main\java\com\blokkok\modsys\communication\BroadcastCommunication.kt: (8, 32): Unresolved reference: Subscription
e: C:\Users\Mark\Downloads\blokkok\submodules\blokkok-modsys\module-system\src\main\java\com\blokkok\modsys\communication\CommunicationContext.kt: (5, 41): Unresolved reference: objects
e: C:\Users\Mark\Downloads\blokkok\submodules\blokkok-modsys\module-system\src\main\java\com\blokkok\modsys\communication\CommunicationContext.kt: (6, 41): Unresolved reference: objects
e: C:\Users\Mark\Downloads\blokkok\submodules\blokkok-modsys\module-system\src\main\java\com\blokkok\modsys\communication\CommunicationContext.kt: (8, 36): Unresolved reference: exception
e: C:\Users\Mark\Downloads\blokkok\submodules\blokkok-modsys\module-system\src\main\java\com\blokkok\modsys\communication\CommunicationContext.kt: (9, 36): Unresolved reference: exception
e: C:\Users\Mark\Downloads\blokkok\submodules\blokkok-modsys\module-system\src\main\java\com\blokkok\modsys\communication\CommunicationContext.kt: (10, 36): Unresolved reference: exception
e: C:\Users\Mark\Downloads\blokkok\submodules\blokkok-modsys\module-system\src\main\java\com\blokkok\modsys\communication\CommunicationContext.kt: (11, 36): Unresolved reference: exception
e: C:\Users\Mark\Downloads\blokkok\submodules\blokkok-modsys\module-system\src\main\java\com\blokkok\modsys\communication\CommunicationContext.kt: (66, 19): Unresolved reference: AlreadyDefinedException
e: C:\Users\Mark\Downloads\blokkok\submodules\blokkok-modsys\module-system\src\main\java\com\blokkok\modsys\communication\CommunicationContext.kt: (80, 22): Unresolved reference: NotDefinedException
e: C:\Users\Mark\Downloads\blokkok\submodules\blokkok-modsys\module-system\src\main\java\com\blokkok\modsys\communication\CommunicationContext.kt: (84, 22): Unresolved reference: NotDefinedException
e: C:\Users\Mark\Downloads\blokkok\submodules\blokkok-modsys\module-system\src\main\java\com\blokkok\modsys\communication\CommunicationContext.kt: (88, 19): Unresolved reference: TypeException
e: C:\Users\Mark\Downloads\blokkok\submodules\blokkok-modsys\module-system\src\main\java\com\blokkok\modsys\communication\CommunicationContext.kt: (95, 42): Unresolved reference: Broadcaster
e: C:\Users\Mark\Downloads\blokkok\submodules\blokkok-modsys\module-system\src\main\java\com\blokkok\modsys\communication\CommunicationContext.kt: (100, 19): Unresolved reference: AlreadyDefinedException
e: C:\Users\Mark\Downloads\blokkok\submodules\blokkok-modsys\module-system\src\main\java\com\blokkok\modsys\communication\CommunicationContext.kt: (103, 36): Unresolved reference: Broadcaster
e: C:\Users\Mark\Downloads\blokkok\submodules\blokkok-modsys\module-system\src\main\java\com\blokkok\modsys\communication\CommunicationContext.kt: (104, 13): 'broadcast' overrides nothing
e: C:\Users\Mark\Downloads\blokkok\submodules\blokkok-modsys\module-system\src\main\java\com\blokkok\modsys\communication\CommunicationContext.kt: (117, 76): Unresolved reference: Subscription
e: C:\Users\Mark\Downloads\blokkok\submodules\blokkok-modsys\module-system\src\main\java\com\blokkok\modsys\communication\CommunicationContext.kt: (121, 95): Unresolved reference: Subscription
e: C:\Users\Mark\Downloads\blokkok\submodules\blokkok-modsys\module-system\src\main\java\com\blokkok\modsys\communication\CommunicationContext.kt: (124, 22): Unresolved reference: NotDefinedException
e: C:\Users\Mark\Downloads\blokkok\submodules\blokkok-modsys\module-system\src\main\java\com\blokkok\modsys\communication\CommunicationContext.kt: (128, 22): Unresolved reference: NotDefinedException
e: C:\Users\Mark\Downloads\blokkok\submodules\blokkok-modsys\module-system\src\main\java\com\blokkok\modsys\communication\CommunicationContext.kt: (132, 19): Unresolved reference: TypeException
e: C:\Users\Mark\Downloads\blokkok\submodules\blokkok-modsys\module-system\src\main\java\com\blokkok\modsys\communication\CommunicationContext.kt: (134, 28): Unresolved reference: Subscription
e: C:\Users\Mark\Downloads\blokkok\submodules\blokkok-modsys\module-system\src\main\java\com\blokkok\modsys\communication\CommunicationContext.kt: (153, 19): Unresolved reference: IllegalFlagAccessException

> Task :app:javaPreCompileDebug UP-TO-DATE
> Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
> Task :app:mergeDebugShaders UP-TO-DATE
> Task :app:compileDebugShaders NO-SOURCE
> Task :app:generateDebugAssets UP-TO-DATE
> Task :module-system:mergeDebugShaders UP-TO-DATE
> Task :module-system:compileDebugShaders NO-SOURCE
> Task :module-system:generateDebugAssets UP-TO-DATE
> Task :module-system:packageDebugAssets UP-TO-DATE
> Task :app:mergeDebugAssets UP-TO-DATE
> Task :app:compressDebugAssets UP-TO-DATE
> Task :app:processDebugJavaRes NO-SOURCE
> Task :module-system:processDebugJavaRes NO-SOURCE
> Task :app:checkDebugDuplicateClasses
> Task :app:mergeDebugJniLibFolders UP-TO-DATE
> Task :module-system:mergeDebugJniLibFolders UP-TO-DATE
> Task :module-system:mergeDebugNativeLibs NO-SOURCE
> Task :module-system:stripDebugDebugSymbols NO-SOURCE
> Task :module-system:copyDebugJniLibsProjectOnly UP-TO-DATE
> Task :app:validateSigningDebug UP-TO-DATE
> Task :app:writeDebugAppMetadata UP-TO-DATE
> Task :app:writeDebugSigningConfigVersions UP-TO-DATE
> Task :app:desugarDebugFileDependencies
> Task :app:mergeExtDexDebug

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  C:\Users\Mark\Downloads\blokkok\app\src\debug\google-services.json
  C:\Users\Mark\Downloads\blokkok\app\src\google-services.json
  C:\Users\Mark\Downloads\blokkok\app\google-services.json


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':module-system:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 41s
40 actionable tasks: 5 executed, 35 up-to-date

**Comment by iyxan23** [comment]
hmm, that looks odd, have you tried syncing gradle? or invalidating android studio's cache?

**Comment by bobjoe12131** [comment]
fixed, pressed build
Got an error at 
`blokkok\submodules\blokkok-modsys\module-system\src\main\java\com\blokkok\modsys\communication\BroadcastCommunication.kt`
for
```java
package com.blokkok.modsys.communication

import com.blokkok.modsys.communication.objects.Broadcaster
import com.blokkok.modsys.communication.objects.Subscription

data class BroadcastCommunication(
    val broadcaster: Broadcaster
    val subscribers: ArrayList<Subscription> = ArrayList(),
) : Communication() {
    override val name: String = "broadcast"
}
-----
Unresolved reference: Broadcaster:3
Unresolved reference: Subscription:4
Unresolved reference: Broadcaster:7
Unresolved reference: Subscription:8
```
I am going to restart and retry the steps. do i need to get any of the other projects?
